materials = [
  "SiO_2-bulk"
  , "TiGeO_2-ave_min"
  , "SiO_2-ave_min"
  , "TiGeO_2-ave_min"
  , "SiO_2-ave_min"
  , "TiGeO_2-ave_min"
  , "SiO_2-ave_min"
  , "TiGeO_2-ave_min"
  , "SiO_2-ave_min"
  , "TiGeO_2-ave_min"
  , "SiO_2-ave_min"
  , "TiGeO_2-ave_min"
  , "SiO_2-ave_min"
  , "TiGeO_2-ave_min"
  , "SiO_2-ave_min"
  , "TiGeO_2-ave_min"
  , "SiO_2-ave_min"
  , "TiGeO_2-ave_min"
  , "SiO_2-ave_min"
  , "TiGeO_2-ave_min"
  , "SiO_2-ave_min"
  , "TiGeO_2-ave_min"
  , "SiO_2-ave_min"
  , "TiGeO_2-ave_min"
  , "SiO_2-ave_min"
  , "TiGeO_2-ave_min"
  , "SiO_2-ave_min"
  , "TiGeO_2-ave_min"
  , "SiO_2-ave_min"
  , "TiGeO_2-ave_min"
  , "SiO_2-ave_min"
  , "TiGeO_2-ave_min"
  , "SiO_2-ave_min"
  , "TiGeO_2-ave_min"
  , "SiO_2-ave_min"
  , "TiGeO_2-ave_min"
  , "SiO_2-ave_min"
  , "TiGeO_2-ave_min"
  , "SiO_2-ave_min"
  , "TiGeO_2-ave_min"
  , "SiO_2-ave_min"
  , "TiGeO_2-ave_min"
  , "SiO_2-ave_min"
  , "TiGeO_2-ave_min"
  , "SiO_2-ave_min"
  , "TiGeO_2-ave_min"
  , "SiO_2-ave_min"
  , "TiGeO_2-ave_min"
  , "SiO_2-ave_min"
  , "TiGeO_2-ave_min"
  , "SiO_2-ave_min"
  , "TiGeO_2-ave_min"
  , "SiO_2-ave_min"
]

thicknesses = [
  1
  , 125.33e-9
  , 196.95e-9
  , 125.33e-9
  , 196.95e-9
  , 125.33e-9
  , 196.95e-9
  , 125.33e-9
  , 196.95e-9
  , 125.33e-9
  , 196.95e-9
  , 125.33e-9
  , 196.95e-9
  , 125.33e-9
  , 196.95e-9
  , 125.33e-9
  , 196.95e-9
  , 125.33e-9
  , 196.95e-9
  , 125.33e-9
  , 196.95e-9
  , 125.33e-9
  , 196.95e-9
  , 125.33e-9
  , 196.95e-9
  , 125.33e-9
  , 196.95e-9
  , 125.33e-9
  , 196.95e-9
  , 125.33e-9
  , 196.95e-9
  , 125.33e-9
  , 196.95e-9
  , 125.33e-9
  , 196.95e-9
  , 125.33e-9
  , 196.95e-9
  , 125.33e-9
  , 196.95e-9
  , 125.33e-9
  , 196.95e-9
  , 125.33e-9
  , 196.95e-9
  , 125.33e-9
  , 196.95e-9
  , 125.33e-9
  , 196.95e-9
  , 125.33e-9
  , 196.95e-9
  , 125.33e-9
  , 196.95e-9
  , 125.33e-9
  , 367.301e-9
]
